### ISSUE TITLE
Latest update not working

### ISSUE THREAD

**Issue by superzanti** [doktormerlin/HyperionVisualizer#7]
Fantastic project, but I can't get it working!

I noticed there is no priority value, the latest hyperion requires a priority of 100 or more for the proto-buf to work.

I'm running on port 19445, not logs from hyperion either as if it hasn't ever connected.
android 'hyperion grabber' seems to work fine, so it doesn't have to do with the connection between my android and the hyperion server....

**Comment by doktormerlin** [comment]
I didnt know that hyperion changed something in an update. I will update my setup and have a look at it, but this can take some time.

**Comment by doktormerlin** [comment]
Hey, I just read a bit about hyperion and I think the app works fine.

I should update the readme.md to show proper usage, the application still is in alpha so I havent finished the usability yet.

Could you try the following:

1. Start the "UDP Listener" effect (it should come bundled with Hyperion, I don't know about Hyperion.ng. The Hyperion Remote application has a feature to remotely start effects.
2. Add the IP address and port (it should be 2391) in the Hyperion Visualizer app
3. Press start to start visualizing
4. Have fun with the app (if it works)

Please follow the steps and tell me about the result, I am happy to help if you have any questiond

**Comment by superzanti** [comment]
Ah. That might be the problem.
I'm on Hyperion.NG
I have no effect called "UDP Listener"

Thanks for your help!

**Comment by doktormerlin** [comment]
Maybe try using the UDP Listener effect from the old hyperion repo and use it in hyperion.ng 😊 it might work, I dont know if the effect engine changed
